### ISSUE TITLE
Test modules not installed by dzil?

### ISSUE THREAD

**Issue by szabgab** [ology/Perl-Metrics-Halstead#1]
I tried to setup GitHub Action for this module (to have CI) and even though I ran
```
        dzil authordeps --missing | cpanm --notest
        dzil listdeps --missing | cpanm --notest
```

it is still missing a bunch of modules needed for testing. e.g. `Test::EOL`, `Test::NoTabs`
Details here:
https://github.com/szabgab/Perl-Metrics-Halstead/actions/runs/3310082016/jobs/5463902818

I could install them with extra commands, but I thought dzil was supposed to install them.
 
As I am not familiar with dzil, any idea what's going on?

**Comment by haarg** [comment]
```
dzil authordeps --missing | cpanm --notest
dzil listdeps --develop --missing | cpanm --notest
```

**Comment by ology** [comment]
haarg++ thank you

**Comment by szabgab** [comment]
Thank you!
